// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZkm8fKFl4pK9B7lgWxi0sElksRWcn_c',
    appId: '1:175667805083:android:d68f617484259fe9a2ff3e',
    messagingSenderId: '175667805083',
    projectId: 'tasky-72a30',
    storageBucket: 'tasky-72a30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJaznFxkgDGH3ri50nzwuxoYAGnYsh-iU',
    appId: '1:175667805083:ios:239d979956123f7ba2ff3e',
    messagingSenderId: '175667805083',
    projectId: 'tasky-72a30',
    storageBucket: 'tasky-72a30.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJaznFxkgDGH3ri50nzwuxoYAGnYsh-iU',
    appId: '1:175667805083:ios:239d979956123f7ba2ff3e',
    messagingSenderId: '175667805083',
    projectId: 'tasky-72a30',
    storageBucket: 'tasky-72a30.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );
}
